// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/helper_job_listing.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/helper_job_listing.go -destination ./mock/mock_interactor/mock_helper_job_listing.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
