// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/helper_chat_group_with_sending_job_seeker.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/helper_chat_group_with_sending_job_seeker.go -destination ./mock/mock_interactor/mock_helper_chat_group_with_sending_job_seeker.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
