// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/scout_service_entry_without_gmail.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/scout_service_entry_without_gmail.go -destination ./mock/mock_interactor/mock_scout_service_entry_without_gmail.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
