// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/helper_billing_address.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/helper_billing_address.go -destination ./mock/mock_interactor/mock_helper_billing_address.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
