// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/helper_sending_enterprise.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/helper_sending_enterprise.go -destination ./mock/mock_interactor/mock_helper_sending_enterprise.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
