// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/csv_enterprise.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/csv_enterprise.go -destination ./mock/mock_interactor/mock_csv_enterprise.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
