// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/search_job_information.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/search_job_information.go -destination ./mock/mock_interactor/mock_search_job_information.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
