// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/interactor/scout_service_scout.go
//
// Generated by this command:
//
//	mockgen -source ./usecase/interactor/scout_service_scout.go -destination ./mock/mock_interactor/mock_scout_service_scout.go
//

// Package mock_interactor is a generated GoMock package.
package mock_interactor
