version: '3'
networks:
  autoscout-local-network:
    driver: bridge
services:
  db:
    container_name: autoscout_local_db
    image: mysql:8.0
    platform: linux/amd64
    networks:
      - autoscout-local-network
    ports:
      - 3306:3306
    volumes:
      - .conf/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: autoscout_local
      MYSQL_ROOT_PASSWORD: password
  # バッチ処理のローカルテスト用
  # log出力: docker logs $(docker ps -aqf name=autoscout-server_butler_1)
  # butler:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - autoscout-local-network
  #   volumes:
  #     - $PWD:/go/src/github.com/spaceaiinc/autoscout-server
  #   env_file:
  #     - .env
  #   environment:
  #     APP_ENV: local
  #     APP_SERVICE: batch
  #     DB_HOST: db
  #   depends_on:
  #     - db
  #   command: go run main.go
