package responses

import "github.com/spaceaiinc/autoscout-server/domain/entity"

type SendingJobSeekerDesiredJobInformation struct {
	SendingJobSeekerDesiredJobInformation *entity.SendingJobSeekerDesiredJobInformation `json:"sending_job_seeker_desired_job_information"`
}

func NewSendingJobSeekerDesiredJobInformation(sendingJobSeekerDesiredJobInformation *entity.SendingJobSeekerDesiredJobInformation) SendingJobSeekerDesiredJobInformation {
	return SendingJobSeekerDesiredJobInformation{
		SendingJobSeekerDesiredJobInformation: sendingJobSeekerDesiredJobInformation,
	}
}

type SendingJobSeekerDesiredJobInformationList struct {
	SendingJobSeekerDesiredJobInformationList []*entity.SendingJobSeekerDesiredJobInformation `json:"sending_job_seeker_desired_job_information_list"`
}

func NewSendingJobSeekerDesiredJobInformationList(sendingJobSeekerDesiredJobInformations []*entity.SendingJobSeekerDesiredJobInformation) SendingJobSeekerDesiredJobInformationList {
	return SendingJobSeekerDesiredJobInformationList{
		SendingJobSeekerDesiredJobInformationList: sendingJobSeekerDesiredJobInformations,
	}
}
